(load "stats")

(define (process str f)
  (display str)
  (display f)
  (newline))

(define (report ls)
   (process "n = " (length ls))
   (process "minimum = " (minmax ls <))
   (process "maximum = " (minmax ls >))
   (process "mean = " (mean ls))
   (process "median = " (median ls))
   (process "population variance = " (population-variance ls))
   (process "sample variance = " (sample-variance ls))
   (process "population standard deviation = " (population-standard-deviation ls))
   (process "sample standard deviation = " (sample-standard-deviation ls))
   (process "median deviation = " (median-deviation ls))
   (process "mean deviation = " (mean-deviation ls))
   (process "population skewness = " (population-skewness ls))
   (process "sample skewness = " (sample-skewness ls))
   (process "non-parametric skew = " (non-parametric-skew ls)))

(define n 1000)
(define x (uniform n))
(define y (uniform n))
(display "random uniform distributions")
(newline)
(display "x")
(newline)
(report x)
(display "y")
(newline)
(report y)
(display "x y")
(newline)
(process "covariance = " (covariance x y))
(process "correlation coefficient = " (correlation-coefficient x y))
(define x (sort (randnorm n) <))
(define y (sort (randnorm n) <))
(display "random normal distributions")
(newline)
(display "x")
(newline)
(report x)
(display "y")
(newline)
(report y)
(display "x y")
(newline)
(process "covariance = " (covariance x y))
(process "correlation coefficient = " (correlation-coefficient x y))
